import {
	Globe,
	Send,
	Camera,
	MessageSquare,
	MessageSquareText,
	GamepadIcon,
	Music2Icon,
	Palette,
	Code,
	Phone,
	SquareStack,
	Calendar,
	Mail
} from "lucide-react"

export const iconMap: Record<string, React.ElementType | string> = {
	website: Globe,
	google: "/images/social/chrome.png",
	instagram: "/images/social/instagram.png",
	tiktok: "/images/social/tiktok.png",
	telegram: "/images/social/telegram.png",
	youtube: "/images/social/youtube.png",
	facebook: "/images/social/facebook.png",
	linkedin: "/images/social/linkedin.png",
	twitter: "/images/social/twitter.png",
	whatsapp: "/images/social/whatsapp.png",
	pinterest: "/images/social/pinterest.png",
	threads: Send,
	snapchat: Camera,
	discord: MessageSquare,
	reddit: MessageSquareText,
	twitch: GamepadIcon,
	spotify: Music2Icon,
	behance: Palette,
	dribbble: Palette,
	figma: Palette,
	github: Code,
	portfolio: Globe,
	newsletter: Mail,
	email: Mail,
	phone: Phone,
	linktree: SquareStack,
	calendly: Calendar
}
