/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    tenants: Tenant;
    business_profile: BusinessProfile;
    business_themes: BusinessTheme;
    about_business: AboutBusiness;
    image_galleries: ImageGallery;
    contact_departments: ContactDepartment;
    social_links: SocialLink;
    business_partners: BusinessPartner;
    business_locations: BusinessLocation;
    section_titles: SectionTitle;
    configuration: Configuration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    business_profile: BusinessProfileSelect<false> | BusinessProfileSelect<true>;
    business_themes: BusinessThemesSelect<false> | BusinessThemesSelect<true>;
    about_business: AboutBusinessSelect<false> | AboutBusinessSelect<true>;
    image_galleries: ImageGalleriesSelect<false> | ImageGalleriesSelect<true>;
    contact_departments: ContactDepartmentsSelect<false> | ContactDepartmentsSelect<true>;
    social_links: SocialLinksSelect<false> | SocialLinksSelect<true>;
    business_partners: BusinessPartnersSelect<false> | BusinessPartnersSelect<true>;
    business_locations: BusinessLocationsSelect<false> | BusinessLocationsSelect<true>;
    section_titles: SectionTitlesSelect<false> | SectionTitlesSelect<true>;
    configuration: ConfigurationSelect<false> | ConfigurationSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ar';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  tenant?: (string | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  /**
   * Used for URLs. Example: /[slug]
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role?: ('super-admin' | 'user') | null;
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_profile".
 */
export interface BusinessProfile {
  id: string;
  tenant?: (string | null) | Tenant;
  businessName: string;
  slogan?: string | null;
  logoLight?: (string | null) | Media;
  logoDark?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_themes".
 */
export interface BusinessTheme {
  id: string;
  tenant?: (string | null) | Tenant;
  /**
   * Give your theme a descriptive name
   */
  name: string;
  /**
   * Main brand color
   */
  primaryColor?: string | null;
  /**
   * Supporting brand color
   */
  secondaryColor?: string | null;
  lightBackground: {
    type: 'color' | 'image';
    color?: string | null;
    image?: (string | null) | Media;
  };
  darkBackground: {
    type: 'color' | 'image';
    color?: string | null;
    image?: (string | null) | Media;
  };
  /**
   * Choose the purpose of this theme
   */
  themeType: 'business' | 'personal';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_business".
 */
export interface AboutBusiness {
  id: string;
  tenant?: (string | null) | Tenant;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image_galleries".
 */
export interface ImageGallery {
  id: string;
  tenant?: (string | null) | Tenant;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_departments".
 */
export interface ContactDepartment {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  phone: string;
  whatsapp?: boolean | null;
  telegram?: boolean | null;
  sms?: boolean | null;
  telephone?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_links".
 */
export interface SocialLink {
  id: string;
  tenant?: (string | null) | Tenant;
  platform:
    | 'website'
    | 'instagram'
    | 'tiktok'
    | 'telegram'
    | 'facebook'
    | 'linkedin'
    | 'youtube'
    | 'twitter'
    | 'portfolio'
    | 'pinterest'
    | 'github'
    | 'whatsapp'
    | 'threads'
    | 'snapchat'
    | 'discord'
    | 'reddit'
    | 'twitch'
    | 'spotify'
    | 'behance'
    | 'dribbble'
    | 'figma'
    | 'newsletter'
    | 'email'
    | 'phone'
    | 'linktree'
    | 'calendly';
  label: string;
  url: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_partners".
 */
export interface BusinessPartner {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  logo: string | Media;
  website?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_locations".
 */
export interface BusinessLocation {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  description?: string | null;
  googleMapLink?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section_titles".
 */
export interface SectionTitle {
  id: string;
  tenant?: (string | null) | Tenant;
  sectionType: 'about' | 'contact' | 'social' | 'partners' | 'locations' | 'gallery';
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration".
 */
export interface Configuration {
  id: string;
  tenant: string | Tenant;
  /**
   * Example: https://domain.com/{tenantId}
   */
  staticUrl: string;
  /**
   * Auto-generated QR URL
   */
  qrUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'business_profile';
        value: string | BusinessProfile;
      } | null)
    | ({
        relationTo: 'business_themes';
        value: string | BusinessTheme;
      } | null)
    | ({
        relationTo: 'about_business';
        value: string | AboutBusiness;
      } | null)
    | ({
        relationTo: 'image_galleries';
        value: string | ImageGallery;
      } | null)
    | ({
        relationTo: 'contact_departments';
        value: string | ContactDepartment;
      } | null)
    | ({
        relationTo: 'social_links';
        value: string | SocialLink;
      } | null)
    | ({
        relationTo: 'business_partners';
        value: string | BusinessPartner;
      } | null)
    | ({
        relationTo: 'business_locations';
        value: string | BusinessLocation;
      } | null)
    | ({
        relationTo: 'section_titles';
        value: string | SectionTitle;
      } | null)
    | ({
        relationTo: 'configuration';
        value: string | Configuration;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_profile_select".
 */
export interface BusinessProfileSelect<T extends boolean = true> {
  tenant?: T;
  businessName?: T;
  slogan?: T;
  logoLight?: T;
  logoDark?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_themes_select".
 */
export interface BusinessThemesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  primaryColor?: T;
  secondaryColor?: T;
  lightBackground?:
    | T
    | {
        type?: T;
        color?: T;
        image?: T;
      };
  darkBackground?:
    | T
    | {
        type?: T;
        color?: T;
        image?: T;
      };
  themeType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_business_select".
 */
export interface AboutBusinessSelect<T extends boolean = true> {
  tenant?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image_galleries_select".
 */
export interface ImageGalleriesSelect<T extends boolean = true> {
  tenant?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_departments_select".
 */
export interface ContactDepartmentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  phone?: T;
  whatsapp?: T;
  telegram?: T;
  sms?: T;
  telephone?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social_links_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  tenant?: T;
  platform?: T;
  label?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_partners_select".
 */
export interface BusinessPartnersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business_locations_select".
 */
export interface BusinessLocationsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  googleMapLink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section_titles_select".
 */
export interface SectionTitlesSelect<T extends boolean = true> {
  tenant?: T;
  sectionType?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configuration_select".
 */
export interface ConfigurationSelect<T extends boolean = true> {
  tenant?: T;
  staticUrl?: T;
  qrUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}