import {
	Instagram,
	Globe,
	Video,
	Send,
	Youtube,
	Facebook,
	Linkedin,
	Twitter,
	MessageCircle,
	Bookmark,
	Camera,
	MessageSquare,
	MessageSquareText,
	GamepadIcon,
	Music2Icon,
	Palette,
	Code,
	Phone,
	SquareStack,
	Calendar,
	Mail
} from "lucide-react"

export const iconMap: Record<string, React.ElementType> = {
	website: Globe,
	instagram: Instagram,
	tiktok: Video,
	telegram: Send,
	youtube: Youtube,
	facebook: Facebook,
	linkedin: Linkedin,
	twitter: Twitter,
	whatsapp: MessageCircle,
	pinterest: Bookmark,
	threads: Send,
	snapchat: Camera,
	discord: MessageSquare,
	reddit: MessageSquareText,
	twitch: GamepadIcon,
	spotify: Music2Icon,
	behance: Palette,
	dribbble: Palette,
	figma: Palette,
	github: Code,
	portfolio: Globe,
	newsletter: Mail,
	email: Mail,
	phone: Phone,
	linktree: SquareStack,
	calendly: Calendar
}
